### ISSUE TITLE
Rename this repo to HCPSS Web Style Guide

### ISSUE THREAD

**Issue by hcpss-mbarger** [hcpss-vincevince1006/fractal-guide-test#1]
@hcpss-vincevince1006 - You've done such a nice job with this guide that I think we need to make it official.  Let's rename the repo (`web-style-guide`) and I'll move it to the HCPSS organization when I get back.

**Comment by hcpss-mbarger** [comment]
Unless what you think we should do instead is merge Fractal and the documented patterns into the [main site theme repo](https://github.com/HCPSS/main-site-theme)?  I.e. the style guide is the central point of reference for the Sass and Gulp build process.

Perhaps that makes more sense.

**Comment by hcpss-vincevince1006** [comment]
Thanks! I think for now it can be it's own repo because I'm still working out a few kinks with the build process. Ball parking completion, I'd say it's 70% there.
